### ISSUE TITLE
ДЗ 7-8 frontend

### ISSUE THREAD

**Issue by PakhomovaN** [PakhomovaN/7-8-frontend#1]
Http.postRequest('/posts', (evt) => {
        loadData();
        contentEl.value = '';
        localStorage.removeItem('link');
    }, handleError, JSON.stringify(data), [{name: 'Content-Type', value: 'application/json'}]);

Консоль пишет, что это не функция, не могу это исправить

**Comment by coursar** [comment]
Всё опечатки - см #2

**Comment by PakhomovaN** [comment]
Все исправила, но консоль пишет то же самое

**Comment by coursar** [comment]
Не пишет же, на Deployment проверил. Возможно, у вас какая-то локальная ошибка.
